apiVersion: v1
kind: Service
metadata:
  name: memory-box-n8n
  labels:
    app: memory-box-n8n
spec:
  selector:
    app: memory-box-n8n
  ports:
    - port: 5678
      targetPort: 5678
      name: http
  type: NodePort
